- name: Post-provision and Configuration
  hosts: all
  vars_files:
       - vars
  become: false
  tasks:
   - name: Download the Apache installer
     win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\Users\httpd-2.2.25-win32-x86-no_ssl.msi
   - name: Install MSI
     win_package:
        path: C:\Users\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
   - name: Download all the Required pkgs from s3 bucket
     environment:
       ansible python module location: /usr/local/lib/python3.7/site-packages/ansible
       ansible collection location: /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
     amazon.aws.s3_object:
         profile: personal 
         bucket: "etl-binaries"
         object: /"SQLServer2016-SSEI-Eval.exe"
         dest: C:\users\SQLServer2016-SSEI-Eval.exe
         mode: get
     register: getresult
   - debug :
         msg = "{{ getresult.msg }}"
     when: getresult.changed