---
- name: Post-provision and Configuration
  hosts: all
  vars_files: 
       - vars
  become: false
  tasks:
   - name: Download the Apache installer
     win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\Users\httpd-2.2.25-win32-x86-no_ssl.msi
   - name: Install MSI
     win_package:
        path: C:\Users\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
   - name: get s3 file
     aws_s3:
      bucket: "etl-binaries"
      object: /SQLServer2016-SSEI-Eval.exe
      dest: /home/ec2-user/etl-binaries/SQLServer2016-SSEI-Eval.exe
      mode: get
     delegate_to: localhost
   - name: copy to win server
     win_copy:
      src: /home/ec2-user/etl-binaries/SQLServer2016-SSEI-Eval.exe
      dest: C:\Users\SQLServer2016-SSEI-Eval.exe

      
  
     


      
  
     

 
  

