---
- name: Post-provision and Configuration
  hosts: all
  vars_files:
       - vars
  become: false
  vars:
    ansible_become_password: "{{ ansible_password }}"
  tasks:
   - name: Copy folder contents recursively
     win_copy:
      src: "{{ src_path }}"
      dest: "{{ dest_path }}"
      remote_src: no

   - name: Install SQLServer2016-SSEI-Eval
     win_command: cmd.exe /k C:\Users\SQLServer2016-SSEI-Eval.exe /Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS
     become: yes
     become_method: runas
     become_user: "{{ ansible_user }}"

   - name: Install SQLServer2016SP3
     win_command: cmd.exe /k C:\Users\SQLServer2016SP3-KB5003279-x64-ENU /Q /ACTION=Install /IACCEPTSQLSERVERLICENSETERMS
     become: yes
     become_method: runas
     become_user: "{{ ansible_user }}"

   - name: Install MSI
     win_package:
        path: C:\Users\SSISPowerPackSetup_64bit_Trial.msi
        state: present

   - name: Install SSDT-Setup-ENU
     win_command: cmd.exe /k C:\Users\SSDT-Setup-ENU.exe /quiet /acceptEula
     become: yes
     become_method: runas
     become_user: "{{ ansible_user }}"

   - name: PSCX
     win_shell: cmd Find-Package pscx | ? ProviderName -eq PSModule | Install-Package -Force

   - name: unpack
     win_shell: Expand-Archive -LiteralPath C:\Users\PROGRESS_DATADIRECT_ODBC_SYBASEASE_AIX_64.zip -DestinationPath C:\Users\

  #  - name: Install DevartODBCASE
  #    win_command: cmd.exe /k C:\Users\DevartODBCASE.exe /Q /ACTION=Install /IACCEPTTHEAGREEMENT /LICENSEINFORMATION=Trial
  #    become: yes
  #    become_method: runas
  #    become_user: Administrator
